### ISSUE TITLE
运行demo1报错

### ISSUE THREAD

**Issue by MyGubooy** [bytesc/Image_Recognition_WebGUI#8]
Traceback (most recent call last):
  File "C:\Users\86138\Desktop\ptuwork\Image_Recognition_WebGUI-main\demo01.py", line 341, in <module>
    pywebio.platform.start_server(
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\pywebio\platform\tornado.py", line 291, in start_server
    _, port = _setup_server(webio_handler=handler, port=port, host=host, static_dir=static_dir,
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\pywebio\platform\tornado.py", line 205, in _setup_server
    server = app.listen(port, address=host, max_buffer_size=max_buffer_size)
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\86138\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by MyGubooy** [comment]
我已经按照了requirement下载了相关库。torch已更新到2.2.0了。百度了是说在写PyTorch网络模型时出现以下报错：
NotImplementedError，该错误表示尚未成功的实现某种方法。这是为什么呀~求大佬解答

**Comment by MyGubooy** [comment]
哭了 我用轻量级版本的之前可以跑通，现在换回跑那个也不行，我在这期间忘记了我之前开了轻量级版本，kill了那个轻量级版本的端口号，就不行啦？求大佬赐教

**Comment by MyGubooy** [comment]
https://blog.csdn.net/lojloj/article/details/106798230 找到解决方法了，应该是版本问题。有遇到同样文图的可以通过这篇文章即可解决哈
